-- Schema inicial para Sistema de Gerenciamento de Filas — 56ª ZE

-- 1. TABELA DE PERFIS (Extensão do Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    perfil TEXT NOT NULL CHECK (perfil IN ('admin', 'atendente')),
    ativo BOOLEAN DEFAULT true,
    primeiro_acesso BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Habilitar RLS nos Perfis
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para Perfis
CREATE POLICY "Qualquer usuário logado pode ler perfis" 
    ON public.profiles FOR SELECT 
    USING (auth.role() = 'authenticated');

CREATE POLICY "Apenas admins podem inserir/editar perfis" 
    ON public.profiles FOR ALL 
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() AND profiles.perfil = 'admin'
        )
    );

-- 2. TABELA DE CONFIGURAÇÃO DE DIAS
CREATE TABLE IF NOT EXISTS public.configuracao_dias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE UNIQUE NOT NULL,
    limite_senhas INTEGER NOT NULL DEFAULT 500,
    bloqueado BOOLEAN DEFAULT false,
    periodo INTEGER NOT NULL CHECK (periodo IN (1, 2)),
    dia_especial BOOLEAN DEFAULT false,
    observacao TEXT,
    ciclo_atual INTEGER DEFAULT 0, -- 0-3 (P1, P2, N1, R1)
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Habilitar RLS em Configurações
ALTER TABLE public.configuracao_dias ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para Configurações
CREATE POLICY "Qualquer usuário logado pode ler configurações de dias" 
    ON public.configuracao_dias FOR SELECT 
    USING (auth.role() = 'authenticated');

CREATE POLICY "Apenas admins podem modificar configurações de dias" 
    ON public.configuracao_dias FOR ALL 
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() AND profiles.perfil = 'admin'
        )
    );

-- 3. TABELA DE ELEITORES NA FILA
CREATE TABLE IF NOT EXISTS public.eleitores_fila (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    data_nascimento DATE NOT NULL,
    pcd BOOLEAN DEFAULT false,
    prioritario BOOLEAN DEFAULT false,
    dia_atendimento DATE NOT NULL REFERENCES public.configuracao_dias(data),
    senha INTEGER NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('presencial', 'agendado')),
    fila TEXT NOT NULL CHECK (fila IN ('prioritaria', 'normal', 'retorno')),
    ordem_manual INTEGER,
    status TEXT NOT NULL DEFAULT 'aguardando' CHECK (status IN ('aguardando', 'chamado', 'atendido', 'ausente', 'cancelado')),
    horario_cadastro TIMESTAMPTZ DEFAULT now(),
    horario_retorno TIMESTAMPTZ,
    horario_chamada TIMESTAMPTZ,
    horario_finalizacao TIMESTAMPTZ,
    remarcado_de DATE,
    remarcacao_count INTEGER DEFAULT 0,
    retorno_count INTEGER DEFAULT 0,
    servidor_cadastro_id UUID REFERENCES public.profiles(id),
    servidor_atendimento_id UUID REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Índices úteis
CREATE INDEX idx_fila_dia ON public.eleitores_fila (dia_atendimento, status);
CREATE INDEX idx_fila_senha ON public.eleitores_fila (dia_atendimento, senha);

-- Habilitar RLS na Fila
ALTER TABLE public.eleitores_fila ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para Fila
CREATE POLICY "Qualquer usuário logado pode ler a fila" 
    ON public.eleitores_fila FOR SELECT 
    USING (auth.role() = 'authenticated');

CREATE POLICY "Usuários autenticados podem inserir/editar na fila" 
    ON public.eleitores_fila FOR ALL 
    USING (auth.role() = 'authenticated');

-- 4. TABELA DE LOG DE AÇÕES
CREATE TABLE IF NOT EXISTS public.log_acoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servidor_id UUID REFERENCES public.profiles(id) NOT NULL,
    acao TEXT NOT NULL,
    eleitor_id UUID REFERENCES public.eleitores_fila(id),
    timestamp TIMESTAMPTZ DEFAULT now(),
    detalhes JSONB
);

-- Habilitar RLS nos Logs
ALTER TABLE public.log_acoes ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para Logs
CREATE POLICY "Qualquer usuário logado pode ler logs" 
    ON public.log_acoes FOR SELECT 
    USING (auth.role() = 'authenticated');

CREATE POLICY "Qualquer usuário logado pode inserir logs" 
    ON public.log_acoes FOR INSERT 
    WITH CHECK (auth.role() = 'authenticated');

-- 5. TABELA DE CONFIGURAÇÃO GLOBAL (CHAVE-VALOR)
CREATE TABLE IF NOT EXISTS public.configuracao_sistema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave TEXT UNIQUE NOT NULL,
    valor TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Políticas RLS Configuração Global
ALTER TABLE public.configuracao_sistema ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública configuracoes" ON public.configuracao_sistema FOR SELECT USING (true);
CREATE POLICY "Admin controla configuracoes" ON public.configuracao_sistema FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND perfil = 'admin')
);

-- 6. TRIGGER PARA CRIAR PERFIL AUTOMATICAMENTE (OPCIONAL, JÁ QUE O FRONT TRATA MAS É SEGURO)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, nome, email, perfil, primeiro_acesso)
    VALUES (
        new.id, 
        COALESCE(new.raw_user_meta_data->>'nome', 'Servidor'), 
        new.email, 
        COALESCE(new.raw_user_meta_data->>'perfil', 'atendente'),
        true
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 7. REALTIME
-- Habilitar realtime para a fila
ALTER PUBLICATION supabase_realtime ADD TABLE public.eleitores_fila;
ALTER PUBLICATION supabase_realtime ADD TABLE public.configuracao_dias;

-- 8. FUNÇÃO RPC PARA OBTER TIMESTAMP DO SERVIDOR
-- Usada para evitar manipulação de data/hora no cliente
CREATE OR REPLACE FUNCTION public.get_server_timestamp()
RETURNS TIMESTAMPTZ
LANGUAGE SQL
SECURITY DEFINER
AS $$
    SELECT now();
$$;
